# Generated by Django 3.2.8 on 2021-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion',
            field=models.CharField(choices=[('done', 'DONE'), ('not done', 'NOT DONE')], max_length=200),
        ),
    ]
